# Generated by Django 5.2.8 on 2025-11-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_querys"),
    ]

    operations = [
        migrations.CreateModel(
            name="iicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=11)),
            ],
        ),
    ]
