# Generated by Django 5.2.8 on 2025-11-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_iicinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="iicinfo",
            name="home",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
