# Generated by Django 5.2.8 on 2025-12-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_notice_options_meeting_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
