# Generated by Django 5.2.8 on 2025-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_notice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='support',
            field=models.FileField(blank=True, null=True, upload_to='meeting/pdfs/'),
        ),
    ]
