# Generated by Django 5.2.8 on 2025-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rnd", "0006_basicdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="support",
            field=models.FileField(blank=True, null=True, upload_to="rnd/pdfs/"),
        ),
        migrations.AddField(
            model_name="bookchapter",
            name="support",
            field=models.FileField(blank=True, null=True, upload_to="rnd/pdfs/"),
        ),
        migrations.AddField(
            model_name="copyright",
            name="support",
            field=models.FileField(blank=True, null=True, upload_to="rnd/pdfs/"),
        ),
        migrations.AddField(
            model_name="journal",
            name="support",
            field=models.FileField(blank=True, null=True, upload_to="rnd/pdfs/"),
        ),
        migrations.AddField(
            model_name="patent",
            name="support",
            field=models.FileField(blank=True, null=True, upload_to="rnd/pdfs/"),
        ),
    ]
